server:
  port: 8052

spring:
  application:
    name: middleware

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5437}/postrgres_db
    username: ${POSTGRES_USER:adm}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
    properties.hibernate.boot.allow_jdbc_metadata_access: false
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      enable-auto-commit: true
      auto-commit-interval: 1000
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer